services:
  db:
    image: postgis/postgis:16-3.4
    container_name: eurobound_spatial_db
    restart: always
    environment:
      POSTGRES_USER: geouser
      POSTGRES_PASSWORD: geopassword
      POSTGRES_DB: eurobound_spatial_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_spatial_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geouser -d eurobound_spatial_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_spatial_data: {}